<a href="https://colab.research.google.com/github/Gabriel-data/Python_Modelos_para_Tratar_e_Preparar_Dados/blob/main/01_02_Tratar_Valores_Numericos_Calculos_Parte2_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# OBJETIVO: Preparar e tratar dados no Python - parte 2 - cálculos numéricos.

# 0. Preparação do ambiente (carga de dados).

In [5]:
# Importar as bibliotecas
import numpy as np
import pandas as pd
import xlrd
import seaborn as sb
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter

In [15]:
### Montar o Drive
from google.colab import drive
# drive.mount('/content/drive')
drive.mount('/content/drive/MyDrive/A-Colab_Note_2')

Mounted at /content/drive/MyDrive/A-Colab_Note_2

In [13]:
## Alternativa para Montar o Drive
import os
#pasta = "/content/drive/MyDrive"
pasta = "/content/drive/MyDrive/A-Colab_Note_2"
if not os.path.exists(pasta):
  os.makedirs(pasta)

In [64]:
# CARREGAR O DATASET em formato Excel, tipo de arquivo .CSV.

# O arquivo na origem possui mais de uma planilha, por isso foi acrescentado um direcionamento para a Lista (planilha).

dados = pd.read_csv('/content/drive/MyDrive/A-Colab_Note_2/MyDrive/A-Colab_Note_2/z_Bases/Lista_20_Prod-Tratada_Etapa_1_falta_Precos.CSV')

## Regras de Negócios para os campos com valores:

		*   PRECO_VISTA = VALOR_CUSTO + 50%
		*   PRECO_PRAZO = PRECO_VISTA + 10
		*   TOTAL_VLR_CUSTO = VALOR_CUSTO * quantidade de Estoque
		*   TOTAL_VLR_VENDA = PRECO_VISTA * quantidade de Estoque

# 1. Analisar estrutura da base de dados

Nome do arquivo: **Lista_20_Produtos_Isol.CSV**

Origem do arquivo: Local, da máquina de usuário.

Responsável (usuário chave): Gabriel Silva

Característica geral e objetivo do arquivo: armazena uma lista única e completa de produtos (SKU), informações de características (marca, categoria), informações financeiras (estoque movimentado, preço de custo, preço de venda e totalizadores) e informações sobre a movimentação de pedidos (pedido, data_movimento, vendedores).

Armazenamento para tratativas: Google Drive / Gabriel

Integração direta: Não

### Campos (Todos)

##### Produto (SKU), TITULO, MARCA, CATEGORIA, VALOR_CUSTO, PRECO_VISTA, PRECO_PRAZO, ESTOQUE, TOTAL_VLR_CUSTO, TOTAL_VLR_VENDA, Estado, Pais, Pedido, Data_Movimento, Vendedor.

### Campos (a serem tratados e visualizados):

#### SKU, TITULO, VALOR_CUSTO, PRECO_VISTA, PRECO_PRAZO, ESTOQUE, TOTAL_VLR_CUSTO, TOTAL_VLR_VENDA.

In [17]:
# CONTAR O NÚMERO TOTAL DE LINHAS E COLUNAS DO DATASET

dados.shape

# Resultado: O número total de linhas é 18 e o número total de colunas é 15.

(18, 15)

In [25]:
# CONSULTAR A ESTRUTURA GERAL DO DATASET

dados.head(3)

# Resultado: positivo, está de acordo com o arquivo de origem que foi carretado.

,SKU,TITULO,MARCA,CATEGORIA,VALOR_CUSTO,PRECO_VISTA,PRECO_PRAZO,ESTOQUE,TOTAL_VLR_CUSTO,TOTAL_VLR_VENDA,Estado,Pais,Pedido,Data_Movimento,Vendedor
0,XYZ102030,Item 1,Amazon,Eletronico,300,450,495,10,3000,4500,Rio Grande do Sul,Brasil,214401,2024-12-09,Cleber
1,XYZ102031,Item 2,IBM,Eletronico,650,975,1072,20,13000,19500,Rio Grande do Sul,Brasil,540247,2023-08-10,Fonseca
2,XYZ102032,Item 3,Google,Internet,900,1350,1485,30,27000,40500,São Paulo,Brasil,367707,2022-12-18,Ana

In [24]:
# IDENTIFICAR TIPOS DE CAMPOS
dados.dtypes


# TRATAR (CONVERTER) TIPOS DE CAMPOS

# Convertendo para float
#dados['PRECO_VISTA'] = dados['PRECO_VISTA'].astype('int64')

# Consulta após conversão dos tipos
#print(dados.dtypes)

# Resultado da análise: Não requerido alterações, todos os campos de valores são do tipo Int65.

SKU                object
TITULO             object
MARCA              object
CATEGORIA          object
VALOR_CUSTO         int64
PRECO_VISTA         int64
PRECO_PRAZO         int64
ESTOQUE             int64
TOTAL_VLR_CUSTO     int64
TOTAL_VLR_VENDA     int64
Estado             object
Pais               object
Pedido              int64
Data_Movimento     object
Vendedor           object
dtype: object

In [65]:
# EXTRAIR NOME DOS CAMPOS DO DATASET

# Finalidade: listar o nome dos campos separados por vírgula.

colunas = dados.columns.tolist()
descricao_campos = ', '.join(colunas)

print(descricao_campos)

SKU, TITULO, MARCA, CATEGORIA, VALOR_CUSTO, PRECO_VISTA, PRECO_PRAZO, ESTOQUE, TOTAL_VLR_CUSTO, TOTAL_VLR_VENDA, Estado, Pais, Pedido, Data_Movimento, Vendedor

In [66]:
# Extrair número campos

colunas = dados.columns.tolist()
descricao_campos = ', '.join([f'{coluna} ({i})' for i, coluna in enumerate(colunas)])

print(descricao_campos)

# Resultado (de quais campos preciso?):
# SKU (0), TITULO (1), VALOR_CUSTO (4), PRECO_VISTA (5), PRECO_PRAZO (6), ESTOQUE (7),TOTAL_VLR_CUSTO (8), TOTAL_VLR_VENDA (9).

SKU (0), TITULO (1), MARCA (2), CATEGORIA (3), VALOR_CUSTO (4), PRECO_VISTA (5), PRECO_PRAZO (6), ESTOQUE (7), TOTAL_VLR_CUSTO (8), TOTAL_VLR_VENDA (9), Estado (10), Pais (11), Pedido (12), Data_Movimento (13), Vendedor (14)

In [67]:
## EXIBIR LINHAS E COLUNAS ESPECÍFICAS

#dados.head(10)

## Exibir entre linhas
#dados.iloc[1:20]

## Exibir linhas e colunas específicas
#dados1.iloc[[2,5,17], [0,1,2,5]]

## Exibir colunas específicas
#print(dados.iloc[:, [2, 6]])
dados.iloc[:5, [0,1,4,5,6,7,8,9]]

## Exibir linhas específicas
#dados.iloc[[2,19]]

,SKU,TITULO,VALOR_CUSTO,PRECO_VISTA,PRECO_PRAZO,ESTOQUE,TOTAL_VLR_CUSTO,TOTAL_VLR_VENDA
0,XYZ102030,Item 1,300,450,495,10,3000,4500
1,XYZ102031,Item 2,650,975,1072,20,13000,19500
2,XYZ102032,Item 3,900,1350,1485,30,27000,40500
3,XYZ102033,Item 4,6500,9750,10725,10,65000,97500
4,XYZ102034,Item 5,650,975,1072,50,32500,48750

### Validando regras:

    *   Dataset contendo campos de valores: (SKU, Título, Categoria, Valor de Custo, Preço à Vista, Preço a Prazo, Estado, Vendedor etc.)
    *   Identificar as regras de negócio quanto aos valores.
		*   PRECO_VISTA = VALOR_CUSTO + 50%
		*   PRECO_PRAZO = PRECO_VISTA + 10
		*   TOTAL_VLR_CUSTO = VALOR_CUSTO * quantidade de Estoque
		*   TOTAL_VLR_VENDA = PRECO_VISTA * quantidade de Estoque
    *   Elaborar plano e ajustar.

In [102]:
# RESERVANDO UMA CÓPIA DO DATASET ORIGINAL

d3 = dados.copy()

In [142]:
# VALIDANDO CÁLCULOS, CONFORME REGRAS:

# REGRA 1-4
##############################################################################
#   PRECO_VISTA = VALOR_CUSTO + 50%

    # Criando a coluna de validação
#d2['Val_PRECO_VISTA'] = d2['PRECO_VISTA'] == d2['VALOR_CUSTO'] * 1.5
d2['Val_PRECO_VISTA'] = d2['PRECO_VISTA_REC'] == d2['VALOR_CUSTO'] * 1.5

    # Retornar resultados como "FALSE", ou seja com erros:
erros = d2[d2['Val_PRECO_VISTA'] == False]

print(erros)

##############################################################################

# Criando um novo campo para recálculo com base na regra:

#d2['PRECO_VISTA_REC'] = (dados['VALOR_CUSTO'] * 1.5).round(0).astype(int)


##############################################################################

# RECONFERE REGRA ↑

Empty DataFrame
Columns: [SKU, TITULO, MARCA, CATEGORIA, VALOR_CUSTO, PRECO_VISTA, PRECO_PRAZO, ESTOQUE, TOTAL_VLR_CUSTO, TOTAL_VLR_VENDA, Estado, Pais, Pedido, Data_Movimento, Vendedor, Val_PRECO_VISTA, PRECO_VISTA_REC, Val_PRECO_PRAZO, PRECO_PRAZO_REC, Val_TOTAL_VLR_CUSTO, Val_TOTAL_VLR_VENDA, TOTAL_VLR_VENDA_REC]
Index: []

[0 rows x 22 columns]

In [141]:
# VALIDANDO CÁLCULOS, CONFORME REGRAS:

# REGRA 2-4
##############################################################################
#   PRECO_PRAZO = PRECO_VISTA + 10%

    # Criando a coluna de validação
#2['Val_PRECO_PRAZO'] = d2['PRECO_PRAZO'] == d2['PRECO_VISTA_REC'] * 1.1
#d2['Val_PRECO_PRAZO'] = d2['PRECO_PRAZO_REC'] == d2['PRECO_VISTA_REC'] * 1.1
d2['Val_PRECO_PRAZO'] = d2['PRECO_PRAZO_REC'] == (d2['PRECO_VISTA_REC'] * 1.1).round(0).astype(int)


    # Retornar resultados como "FALSE", ou seja com erros:
erros = d2[d2['Val_PRECO_PRAZO'] == False]

print(erros)

##############################################################################

# Criando um novo campo para recálculo com base na regra:

#d2['PRECO_PRAZO_REC'] = (d2['PRECO_VISTA_REC'] * 1.1).round(0).astype(int)


##############################################################################

# RECONFERE REGRA ↑

Empty DataFrame
Columns: [SKU, TITULO, MARCA, CATEGORIA, VALOR_CUSTO, PRECO_VISTA, PRECO_PRAZO, ESTOQUE, TOTAL_VLR_CUSTO, TOTAL_VLR_VENDA, Estado, Pais, Pedido, Data_Movimento, Vendedor, Val_PRECO_VISTA, PRECO_VISTA_REC, Val_PRECO_PRAZO, PRECO_PRAZO_REC, Val_TOTAL_VLR_CUSTO, Val_TOTAL_VLR_VENDA, TOTAL_VLR_VENDA_REC]
Index: []

[0 rows x 22 columns]

In [140]:
# VALIDANDO CÁLCULOS, CONFORME REGRAS:

# REGRA 3-4
##############################################################################
# TOTAL_VLR_CUSTO = VALOR_CUSTO * quantidade de Estoque

    # Criando a coluna de validação
d2['Val_TOTAL_VLR_CUSTO'] = (d2['VALOR_CUSTO'] * d2['ESTOQUE']) == d2['TOTAL_VLR_CUSTO']

    # Retornar resultados como "FALSE", ou seja com erros:
erros = d2[d2['Val_TOTAL_VLR_CUSTO'] == False]

print(erros)

##############################################################################

# Criando um novo campo para recálculo com base na regra:

 #d2['TOTAL_VLR_CUSTO_REC'] = (dados['PRECO_CUSTO'] * dados['ESTOQUE']).astype(int)


##############################################################################

# RECONFERE REGRA ↑

Empty DataFrame
Columns: [SKU, TITULO, MARCA, CATEGORIA, VALOR_CUSTO, PRECO_VISTA, PRECO_PRAZO, ESTOQUE, TOTAL_VLR_CUSTO, TOTAL_VLR_VENDA, Estado, Pais, Pedido, Data_Movimento, Vendedor, Val_PRECO_VISTA, PRECO_VISTA_REC, Val_PRECO_PRAZO, PRECO_PRAZO_REC, Val_TOTAL_VLR_CUSTO, Val_TOTAL_VLR_VENDA, TOTAL_VLR_VENDA_REC]
Index: []

[0 rows x 22 columns]

In [139]:
# VALIDANDO CÁLCULOS, CONFORME REGRAS:

# REGRA 4-4
##############################################################################
# TOTAL_VLR_VENDA = PRECO_VISTA * quantidade de Estoque

    # Criando a coluna de validação
d2['Val_TOTAL_VLR_VENDA'] = (d2['PRECO_VISTA_REC'] * d2['ESTOQUE']) == d2['TOTAL_VLR_VENDA_REC']

    # Retornar resultados como "FALSE", ou seja com erros:
erros = d2[d2['Val_TOTAL_VLR_VENDA'] == False]

print(erros)

##############################################################################

# Criando um novo campo para recálculo com base na regra:

#d2['TOTAL_VLR_VENDA_REC'] = (d2['PRECO_VISTA_REC'] * d2['ESTOQUE']).astype(int)


##############################################################################

# RECONFERE REGRA ↑

Empty DataFrame
Columns: [SKU, TITULO, MARCA, CATEGORIA, VALOR_CUSTO, PRECO_VISTA, PRECO_PRAZO, ESTOQUE, TOTAL_VLR_CUSTO, TOTAL_VLR_VENDA, Estado, Pais, Pedido, Data_Movimento, Vendedor, Val_PRECO_VISTA, PRECO_VISTA_REC, Val_PRECO_PRAZO, PRECO_PRAZO_REC, Val_TOTAL_VLR_CUSTO, Val_TOTAL_VLR_VENDA, TOTAL_VLR_VENDA_REC]
Index: []

[0 rows x 22 columns]

Refazer etaps de validação ↑

In [168]:
# RESERVANDO UMA CÓPIA DO DATASET ORIGINAL

df = d2.copy()

Alternativas

In [184]:
# Extrair número campos (2)

colunas = df.columns.tolist()
descricao_campos = ', '.join([f'{coluna} ({i})' for i, coluna in enumerate(colunas)])

print(descricao_campos)

# Resultado (de quais campos preciso?):
# SKU (0), TITULO (1), VALOR_CUSTO (4), PRECO_VISTA (5), PRECO_PRAZO (6), ESTOQUE (7),TOTAL_VLR_CUSTO (8), TOTAL_VLR_VENDA (9).

SKU (0), TITULO (1), MARCA (2), CATEGORIA (3), VALOR_CUSTO (4), PRECO_VISTA (5), ESTOQUE (6), TOTAL_VLR_CUSTO (7), Estado (8), Pais (9), Pedido (10), Data_Movimento (11), VENDEDORES (12), PRECO_PRAZO (13), TOTAL_VLR_VENDA (14)

In [119]:
## Exibir colunas específicas
#print(dados.iloc[:, [2, 6]])

dados.iloc[:5, [0,1,4,5,6,7,8,9]]

,SKU,TITULO,VALOR_CUSTO,PRECO_VISTA,PRECO_PRAZO,ESTOQUE,TOTAL_VLR_CUSTO,TOTAL_VLR_VENDA
0,XYZ102030,Item 1,300,450,495,10,3000,4500
1,XYZ102031,Item 2,650,975,1072,20,13000,19500
2,XYZ102032,Item 3,900,1350,1485,30,27000,40500
3,XYZ102033,Item 4,6500,9750,10725,10,65000,97500
4,XYZ102034,Item 5,650,975,1072,50,32500,48750

In [194]:
# Identificação de tipos de campo:
dfx.dtypes

SKU                object
TITULO             object
MARCA              object
CATEGORIA          object
VALOR_CUSTO         int64
PRECO_VISTA         int64
ESTOQUE             int64
PRECO_PRAZO         int64
TOTAL_VLR_CUSTO     int64
TOTAL_VLR_VENDA     int64
Estado             object
Pais               object
Pedido              int64
Data_Movimento     object
VENDEDORES         object
dtype: object

In [170]:
# Remoçao de campos (colunas) desnecessárias:

df = df.drop(columns=['PRECO_VISTA', 'PRECO_PRAZO', 'TOTAL_VLR_VENDA', 'Val_TOTAL_VLR_VENDA', 'Val_TOTAL_VLR_CUSTO', 'Val_PRECO_PRAZO', 'Val_PRECO_VISTA'])
#df = df.drop(columns=['Val_TOTAL_VLR_VENDA', 'Val_TOTAL_VLR_CUSTO', 'Val_PRECO_PRAZO', 'Val_PRECO_VISTA'])

In [ ]:
# Coreção de dados em linhas e campos específicos:

# Altera o valor de 'PRECO_VISTA' na linha 17 para 150
dados.loc[17, 'PRECO_VISTA'] = 150


## Exibir colunas específicas
dados.iloc[16:18, [0,1,4,5,8,7,17]]

In [178]:
# Renomear Campos (colunas)

df = df.rename(columns={'PRECO_VISTA_REC': 'PRECO_VISTA', 'Vendedor': 'VENDEDORES'})

In [ ]:
# Renoemar todas as colunas
# Atribuindo nome as colunas

df.columns = ['novo_nome_coluna1', 'novo_nome_coluna2', 'novo_nome_coluna3']

In [183]:
# Remova a coluna da posição original
precovista_coluna = df.pop('PRECO_VISTA')

# Alterar posição de campos
df.insert(5, 'PRECO_VISTA', precovista_coluna)

print(df)

          SKU   TITULO       MARCA       CATEGORIA  VALOR_CUSTO  PRECO_VISTA  \
0   XYZ102030   Item 1      Amazon      Eletronico          300          450
1   XYZ102031   Item 2         IBM      Eletronico          650          975
2   XYZ102032   Item 3      Google        Internet          900         1350
3   XYZ102033   Item 4   Microsoft        Software         6500         9750
4   XYZ102034   Item 5      Amazon      Eletronico          650          975
5   XYZ102035   Item 6  Mastercard         Serviço          650          975
6   XYZ102036   Item 7      Google        Internet          990         1485
7   XYZ102037   Item 8   Microsoft        Software          650          975
8   XYZ102038   Item 9        Dove          Beleza          300          450
9   ABC102039  Item 10        Dove          Beleza          300          450
10  ABC102040  Item 11  Mastercard         Serviço          650          975
11  ABC102041  Item 12      Google        Internet          900         1350
12  ABC102042  Item 13   Microsoft        Software        15000        22500
13  ABC102043  Item 14      Amazon      Eletronico          650          975
14  ABC102044  Item 15       Apple      Eletronico          650          975
15  ABC102045  Item 16      Google        Internet          800         1200
16  ABC102048  Item 19      Disney  Entretenimento          650          975
17  ABC102049  Item 20      Nestle        Nutrição          100          150

    ESTOQUE  TOTAL_VLR_CUSTO             Estado    Pais  Pedido  \
0        10             3000  Rio Grande do Sul  Brasil  214401
1        20            13000  Rio Grande do Sul  Brasil  540247
2        30            27000          São Paulo  Brasil  367707
3        10            65000   Distrito Federal  Brasil  529998
4        50            32500  Rio Grande do Sul  Brasil   42227
5        60            39000       Minas Gerais  Brasil  429278
6        70            69300          São Paulo  Brasil  390903
7        80            52000   Distrito Federal  Brasil   74825
8        90            27000             Paraná  Brasil  113354
9       100            30000             Paraná  Brasil  306315
10      110            71500       Minas Gerais  Brasil     385
11      120           108000          São Paulo  Brasil  351339
12        5            75000   Distrito Federal  Brasil  594614
13      140            91000  Rio Grande do Sul  Brasil  419707
14      150            97500  Rio Grande do Sul  Brasil  282501
15      160           128000          São Paulo  Brasil  178006
16      190           123500     Rio de Janeiro  Brasil  565769
17      200            20000          São Paulo  Brasil  234984

   Data_Movimento VENDEDORES  PRECO_PRAZO  TOTAL_VLR_VENDA
0      2024-12-09     Cleber          495             4500
1      2023-08-10    Fonseca         1072            19500
2      2022-12-18        Ana         1485            40500
3      2024-07-12      Paulo        10725            97500
4      2022-02-16      Diego         1072            48750
5      2023-06-22      Sônia         1072            58500
6      2022-07-12     Cleber         1634           103950
7      2022-04-24    Fonseca         1072            78000
8      2023-11-01        Ana          495            40500
9      2023-11-08      Paulo          495            45000
10     2024-12-29      Diego         1072           107250
11     2022-06-24      Sônia         1485           162000
12     2023-07-22     Cleber        24750           112500
13     2022-06-23    Fonseca         1072           136500
14     2023-04-14        Ana         1072           146250
15     2022-08-29      Paulo         1320           192000
16     2024-03-11     Cleber         1072           185250
17     2024-06-08    Fonseca          165            30000

In [188]:
# RESERVANDO UMA CÓPIA DO DATASET ORIGINAL

dfx = df.copy()

In [193]:
#dfx = pd.Dataframe(df)

# Defina a ordem desejada das colunas por completo
ordem_colunas = ['SKU', 'TITULO', 'MARCA', 'CATEGORIA', 'VALOR_CUSTO', 'PRECO_VISTA', 'ESTOQUE', 'PRECO_PRAZO', 'TOTAL_VLR_CUSTO', 'TOTAL_VLR_VENDA', 'Estado', 'Pais', 'Pedido', 'Data_Movimento', 'VENDEDORES']

# Reordene as colunas do DataFrame
dfx = dfx[ordem_colunas]

In [ ]:
# REVISAR Dataset

dfx.head(20)

Conclusão:

Foram aplicados tratamentos em 4 campos com valores monetários.

## 6. Gerar novo Dataset tratado.



*   Exportar

In [197]:
# Criar cópia renomeada do Dataset

dados2 = dfx.copy()  # Faz uma cópia do DataFrame original

dados2.head(20)

,SKU,TITULO,MARCA,CATEGORIA,VALOR_CUSTO,PRECO_VISTA,ESTOQUE,PRECO_PRAZO,TOTAL_VLR_CUSTO,TOTAL_VLR_VENDA,Estado,Pais,Pedido,Data_Movimento,VENDEDORES
0,XYZ102030,Item 1,Amazon,Eletronico,300,450,10,495,3000,4500,Rio Grande do Sul,Brasil,214401,2024-12-09,Cleber
1,XYZ102031,Item 2,IBM,Eletronico,650,975,20,1072,13000,19500,Rio Grande do Sul,Brasil,540247,2023-08-10,Fonseca
2,XYZ102032,Item 3,Google,Internet,900,1350,30,1485,27000,40500,São Paulo,Brasil,367707,2022-12-18,Ana
3,XYZ102033,Item 4,Microsoft,Software,6500,9750,10,10725,65000,97500,Distrito Federal,Brasil,529998,2024-07-12,Paulo
4,XYZ102034,Item 5,Amazon,Eletronico,650,975,50,1072,32500,48750,Rio Grande do Sul,Brasil,42227,2022-02-16,Diego
5,XYZ102035,Item 6,Mastercard,Serviço,650,975,60,1072,39000,58500,Minas Gerais,Brasil,429278,2023-06-22,Sônia
6,XYZ102036,Item 7,Google,Internet,990,1485,70,1634,69300,103950,São Paulo,Brasil,390903,2022-07-12,Cleber
7,XYZ102037,Item 8,Microsoft,Software,650,975,80,1072,52000,78000,Distrito Federal,Brasil,74825,2022-04-24,Fonseca
8,XYZ102038,Item 9,Dove,Beleza,300,450,90,495,27000,40500,Paraná,Brasil,113354,2023-11-01,Ana
9,ABC102039,Item 10,Dove,Beleza,300,450,100,495,30000,45000,Paraná,Brasil,306315,2023-11-08,Paulo
10,ABC102040,Item 11,Mastercard,Serviço,650,975,110,1072,71500,107250,Minas Gerais,Brasil,385,2024-12-29,Diego
11,ABC102041,Item 12,Google,Internet,900,1350,120,1485,108000,162000,São Paulo,Brasil,351339,2022-06-24,Sônia
12,ABC102042,Item 13,Microsoft,Software,15000,22500,5,24750,75000,112500,Distrito Federal,Brasil,594614,2023-07-22,Cleber
13,ABC102043,Item 14,Amazon,Eletronico,650,975,140,1072,91000,136500,Rio Grande do Sul,Brasil,419707,2022-06-23,Fonseca
14,ABC102044,Item 15,Apple,Eletronico,650,975,150,1072,97500,146250,Rio Grande do Sul,Brasil,282501,2023-04-14,Ana
15,ABC102045,Item 16,Google,Internet,800,1200,160,1320,128000,192000,São Paulo,Brasil,178006,2022-08-29,Paulo
16,ABC102048,Item 19,Disney,Entretenimento,650,975,190,1072,123500,185250,Rio de Janeiro,Brasil,565769,2024-03-11,Cleber
17,ABC102049,Item 20,Nestle,Nutrição,100,150,200,165,20000,30000,São Paulo,Brasil,234984,2024-06-08,Fonseca

In [198]:
# Exportando dados tratados para arquivo de Excel:

dados2.to_excel('/content/drive/MyDrive/A-Colab_Note_2/MyDrive/A-Colab_Note_2/z_Bases/Bases_Tratadas/Lista_20_Precos-Tratada_300325.xlsx', index=False)

In [199]:
# Exportando dados tratados para arquivo de CSV:

dados2.to_csv('/content/drive/MyDrive/A-Colab_Note_2/MyDrive/A-Colab_Note_2/z_Bases/Bases_Tratadas/Lista_20_Precos-Tratada_300325.CSV', index=False)

Próximo tema (PREVISTO):

- Análises quantitativas.

Obrigado por acompanhar até aqui!

Fim!